# -*- coding: utf-8 -*-
"""problem1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9kkdimqMj9SJjxv0aT_-Uh9dj4y2uez
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import fashion_mnist
import wandb

# Initialize wandb
wandb.init(project="A1_DA6401", name="problem1")

#load the dataset
(x_train, y_train), _ = fashion_mnist.load_data()         #only training data is sufficient to plot a sample image from each class
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

#define function to plot the images
def sample_images():
  fig, axes= plt.subplots(1, len(class_names), figsize=(15, 6))
  wandb_images = []
  for i in range(len(class_names)):
    index= np.random.choice(np.where(y_train == i)[0])      #select a random image from each class
    axes[i].imshow(x_train[index], cmap='gray')
    axes[i].set_title(class_names[i])
    axes[i].axis('off')
    wandb_images.append(wandb.Image(x_train[index], caption=class_names[i]))
  plt.tight_layout()
  plt.show()

  # Log images to wandb
  wandb.log({"Sample Images": wandb_images})

sample_images()                                            #function call

wandb.finish()                                          #finish wandb run